config/routes.rb
Rails.application.routes.draw do

  resources :recruiters do
    resources :pings
    resources :merits

    collection do
      get :import
      post :process_import
      get :export
    end

    member do
      post :blacklist
      post :unblacklist
    end
  end

  resources :interviews

  resources :recruiter_lists, path: 'lists'

  resources :blacklists, only: [:index]

  get 'recruiters/typeahead/:query' => 'recruiters#typeahead'

  root 'recruiters#index'

end

app/models/blacklist.rb
class Blacklist < ActiveRecord::Base
  belongs_to :recruiter
  accepts_nested_attributes_for :recruiter

  before_save :default_values

  Colors = ['black', 'gray']
  Demerits = { 'black' => -100, 'gray' => -50 }

  validates :recruiter, :color, :reason, presence: true
  validates :color, inclusion: { in: Colors }
  validates :color, uniqueness: {scope: :recruiter, message: "already %{value}listed"}

  scope :indexed, -> { where(active: true).order('created_at DESC').includes(recruiter: :pings) }

  def active?
    active
  end

  def demerit_value
    Demerits[color]
  end

  private

  def default_values
    self[:active] = true if self[:active].nil?
  end
end

app/controllers/blacklists_controller.rb
class BlacklistsController < ApplicationController

  # GET /blacklists
  def index
    @blacklists = Blacklist.indexed
  end

  # POST /blacklists.json
  # create -> see recruiters#blacklist

  # PUT /blacklists/1.json
  # update -> see recruiters#unblacklist

end

app/helpers/blacklists_helper.rb
module BlacklistsHelper
end

app/views/blacklists/create.js.slim
- if @blacklist.errors
  - @blacklist.errors.full_messages.each do |message|
    - html_f = "<div class='alert alert-danger' role='alert'><strong>%s</strong>: %s</div>"
    - html_msg = format(html_f, 'Blacklist Error', message).html_safe
    |
      $('div.flash.js').html("#{html_msg}").slideDown(500).delay(3000).slideUp(500);
|
  $('div#blacklist-modal').modal('hide');

app/views/blacklists/index.html.slim
h2 Blacklists

table.table.table-striped
  thead
    tr
      th Date
      th Recruiter
      th Email
      th Last Contact
      th Score
      th

  tbody
    - if @blacklists.present?
      - @blacklists.each do | blacklist |
        tr [
          id="blacklist-#{blacklist.id}"
          class='blacklist #{blacklist.color}'
        ]
          td = blacklist.created_at.to_date
          td = link_to blacklist.recruiter.name, recruiter_path(blacklist.recruiter)
          td = blacklist.recruiter.email
          td = (blacklist.recruiter.last_contact.present? ? blacklist.recruiter.last_contact : 'N/A')
          td = blacklist.recruiter.score
          td
            = button_to unblacklist_recruiter_path(blacklist.recruiter),
              remote: true,
              method: :post,
              class:  "btn btn-default unblacklist",
              data: { confirm: "Are you sure?" } \
              do
              = hidden_field_tag 'color', blacklist.color
              span.glyphicon.glyphicon-list aria-hidden="true"
              |  De-list

    - else
      tr
        td.no-records colspan=6 No blacklists yet.