config/routes.rb
Rails.application.routes.draw do

  resources :recruiters do
    resources :pings
    resources :merits

    collection do
      get :import
      post :process_import
      get :export
    end

    member do
      post :blacklist
      post :unblacklist
    end
  end

  resources :interviews

  resources :recruiter_lists, path: 'lists'

  resources :blacklists, only: [:index]

  get 'recruiters/typeahead/:query' => 'recruiters#typeahead'

  root 'recruiters#index'

end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  before_action :set_interview, only: [:show, :edit, :update, :destroy]

  # GET /interviews
  # GET /interviews.json
  def index
    @interviews = Interview.by_date
  end

  # GET /interviews/1
  # GET /interviews/1.json
  def show
  end

  # GET /interviews/new
  def new
    @recruiter = Recruiter.find_or_initialize_by(id: params[:recruiter_id])
    @interview = Interview.new
    @interview.recruiter = @recruiter if @recruiter
    @recruiters = Recruiter.sorted_by_email

    # Default assessment values to 3
    Interview::Assessments.each do |assessment|
      @interview.send(format('%s=', assessment.to_s), 3)
    end
  end

  # GET /interviews/1/edit
  def edit
    @recruiter = Recruiter.find_or_initialize_by(id: params[:recruiter_id])
    @recruiters = Recruiter.all
  end

  # POST /interviews
  # POST /interviews.json
  def create
    @recruiter = Recruiter.find_or_initialize_by(id: params[:recruiter_id])
    @interview = Interview.new(interview_params)
    @recruiters = Recruiter.all

    respond_to do |format|
      if @interview.save
        format.html { redirect_to interviews_path, notice: 'Interview was successfully created.' }
        format.json { render :show, status: :created, location: @interview }
      else
        format.html { render :new }
        format.json { render json: @interview.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interviews/1
  # PATCH/PUT /interviews/1.json
  def update
    respond_to do |format|
      if @interview.update(interview_params)
        format.html { redirect_to interviews_path, notice: 'Interview was successfully updated.' }
        format.json { render :show, status: :ok, location: @interview }
      else
        format.html { render :edit }
        format.json { render json: @interview.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interviews/1
  # DELETE /interviews/1.json
  def destroy
    @interview.destroy
    respond_to do |format|
      format.html { redirect_to interviews_url, notice: 'Interview was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interview
      @interview = Interview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interview_params
      params.require(:interview).permit(:date, :company, :culture, :kind,
        :people, :work, :career, :commute, :salary, :gut, :interviewer, :notes,
        :result,
        :recruiter_id,
        recruiter_attributes: [:id])
    end
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/views/interviews/_form.html.slim
= form_for @interview, {class: 'form-horizontal'} do |f|
  - if @interview.errors.any?
    #error_explanation
      h2 = "#{pluralize(@interview.errors.count, "error")} prohibited this interview from being saved:"
      ul
        - @interview.errors.full_messages.each do |message|
          li = message

  div.two-column.row
    div.col-sm-6.left.assessement
      - [:culture, :people, :work, :career, :commute, :salary, :gut].each do |field|
        div.form-group.row
          div.col-sm-2
          = f.label field, {class: 'col-sm-4 control-label horizontal'}
          div.col-sm-2
            = f.select(field,
              options_for_select((1..5).to_a.reverse, @interview.send(field.to_s)),
              {},
              {class: "form-control"})
          div.col-sm-4

    div.col-sm-6.right
      div.form-group.row
        = f.label :recruiter, {class: 'col-sm-2 control-label horizontal'}
        div.col-sm-7
          = f.select(:recruiter_id,
              options_for_select(@recruiters.map{ |r| [r.email, r.id] }, @interview.recruiter_id),
              {include_blank: 'Choose recruiter below'},
              {class: "form-control"})
        div.col-sm-3

      div.form-group.row
        = f.label :kind, {class: 'col-sm-2 control-label horizontal'}
        div.col-sm-7
          = f.select(:kind,
              options_for_select(Interview::Kinds, @interview.kind),
              {},
              {class: "form-control"})
        div.col-sm-3

      div.form-group.row
        = f.label :company, {class: 'col-sm-2 control-label horizontal'}
        div.col-sm-6
          = f.text_field :company, {class: 'form-control'}
        div.col-sm-4

      div.form-group.row
        = f.label :interviewer, {class: 'col-sm-2 control-label horizontal'}
        div.col-sm-6
          = f.text_field :interviewer, {class: 'form-control'}
        div.col-sm-4

      div.form-group.row
        = f.label :date, {class: 'col-sm-2 control-label horizontal'}
        div.col-sm-4
          div.input-group.date
            = f.text_field :date, {'class' => 'form-control'}
            span.input-group-addon
              i.glyphicon.glyphicon-calendar aria-hidden="true"
        div.col-sm-6

      div.form-group.row
        = f.label :notes, {class: 'col-sm-2 control-label horizontal'}
        div.col-sm-6
          = f.text_area :notes, {class: 'form-control'}
        div.col-sm-4

      div.form-group.row
        = f.label :result, {class: 'col-sm-2 control-label horizontal'}
        div.col-sm-7
          = f.select(:result,
              options_for_select(Interview::Results, @interview.result),
              {},
              {class: "form-control"})
        div.col-sm-3

      div.actions.row
        div.col-md-offset-2.col-sm-10
          = f.submit({class: 'btn btn-primary'})
          a.btn.btn-default href=interviews_path = 'Cancel'

app/views/interviews/_table.html.slim
table.table.table-striped
  thead
    tr
      th Date
      th Company
      th Recruiter
      th Interviewer
      th Total
      th Result
      th

  tbody
    - if interviews.present?
      - interviews.each do |interview|
        tr
          td = interview.date
          td = interview.company
          td = (interview.recruiter ? interview.recruiter.name : 'N/A')
          td = interview.interviewer
          td = interview.value
          td = interview.result
          td
            a.btn.btn-default href=edit_interview_path(interview)
              span.glyphicon.glyphicon-edit aria-hidden="true"
              |  Edit

    - else
      tr
        td.no-records colspan=11 No interviews yet.

app/views/interviews/edit.html.slim
h2 Edit Interview

== render 'form'

app/views/interviews/index.html.slim
h2 Interviews

div.actions
  = link_to 'New Interview', new_interview_path, {class: "btn btn-primary", type: "button"}

== render partial: 'table', locals: {interviews: @interviews}

app/views/interviews/new.html.slim
h2 New Interview

== render 'form'

app/views/interviews/show.html.slim
p#notice = notice

p
  strong Recruiter:
  = @interview.recruiter
p
  strong Date:
  = @interview.date
p
  strong Company:
  = @interview.company
p
  strong Culture:
  = @interview.culture
p
  strong People:
  = @interview.people
p
  strong Work:
  = @interview.work
p
  strong Career:
  = @interview.career
p
  strong Commute:
  = @interview.commute
p
  strong Salary:
  = @interview.salary
p
  strong Gut:
  = @interview.gut

= link_to 'Edit', edit_interview_path(@interview)
'|
= link_to 'Back', interviews_path