config/routes.rb
Rails.application.routes.draw do

  resources :recruiters do
    resources :pings
    resources :merits

    collection do
      get :import
      post :process_import
      get :export
    end

    member do
      post :blacklist
      post :unblacklist
    end
  end

  resources :interviews

  resources :recruiter_lists, path: 'lists'

  resources :blacklists, only: [:index]

  get 'recruiters/typeahead/:query' => 'recruiters#typeahead'

  root 'recruiters#index'

end

app/models/recruiter.rb
class Recruiter < ActiveRecord::Base
  include Sortable

  has_many :pings, dependent: :destroy
  has_many :merits, dependent: :destroy
  has_many :interviews, dependent: :destroy
  has_many :blacklists, dependent: :destroy
  belongs_to :recruiter_list

  before_save :compute_score

  validates :first_name, :email, presence: true
  validates :email, uniqueness: true

  scope :recently_pinged, ->{ joins('LEFT JOIN pings ON pings.recruiter_id = recruiters.id')
    .select('recruiters.*, MIN(pings.date) as first_contact, MAX(pings.date) as last_contact')
    .group('recruiters.id')
    .order('last_contact DESC')
    .includes(:pings) }

  scope :sorted_by_email, ->{ order('email ASC') }

  #
  # Constants
  #
  CSV_PING_MARKER = '----> [PING]'
  CSV_MERIT_MARKER = '----> [MERIT]'

  #
  # Class Methods
  #
  def self.companies
    companies = Recruiter.all.collect do |recruiter|
      recruiter.company
    end
    companies.uniq
  end

  def self.email_company_map
    email_company_map = {}
    Recruiter.all.each do |recruiter|
      _, _, address = recruiter.email.rpartition('@')
      email_company_map[address] = recruiter.company
    end
    email_company_map
  end

  def self.find_existing_company_by_email(email)
    _, _, address = email.rpartition('@')
    self.email_company_map[address]
  end

  def self.create_from_import(row)
    # Map fields to different CSV columns (will vary by source)
    key_map = {
      :first_name => [:first_name],
      :last_name => [:last_name],
      :email => [:email_address, :email],
      #:created_on => [:confirm_time]
    }

    # Invert and flatten key map
    flat_key_tuples = []
    key_map.each do |field, row_keys|
      flat_key_tuples << [field, field]
      row_keys.each do |row_key|
        flat_key_tuples << [row_key, field]
      end
    end
    flat_key_map = Hash[flat_key_tuples]

    # Map keys
    params = {}
    flat_key_map.each do |row_key, field|
      params[field] = row[row_key] if row[row_key]
    end

    # Infer company from email if not set
    if params[:company].nil? && params[:email]
      params[:company] = self.find_existing_company_by_email(params[:email])

      if params[:company].nil?
        _, address = params[:email].split('@')
        address_parts = address.split('.')
        params[:company] = address_parts[-2].titleize
      end
    end

    # Look for recruiter
    recruiter = where(email: params[:email]).first

    # If recruiter exists, look for associated record
    if recruiter

      # Ping row
      if row[:first_name] == CSV_PING_MARKER
        Ping.create(
          recruiter_id: recruiter.id,
          date: row[:'ping.date'],
          kind: row[:'ping.kind'],
          note: row[:'ping.note']
        )
      end

      # Merit row
      if row[:first_name] == CSV_MERIT_MARKER
        Merit.create(
          recruiter_id: recruiter.id,
          date: row[:'merit.date'],
          reason: row[:'merit.reason'],
          value: row[:'merit.value']
        )
      end

    # Create new recruiter
    else
      recruiter = Recruiter.create(params)

      # Add first ping
      if recruiter.persisted?
        recruiter.pings << Ping.create(
          recruiter_id: recruiter.id,
          date: Date.today,
          kind: 'mailchimp import',
          note: 'Imported from CSV file.'
        )
      end
    end

    recruiter
  end

  def self.export_to_csv(options = {})
    direct_export_fields = ['first_name', 'last_name', 'email', 'company', 'phone']
    ping_export_fields = ['ping.kind', 'ping.note', 'ping.date']
    merit_export_fields = ['merit.reason', 'merit.value', 'merit.date']
    other_export_fields = ['score', 'list']

    CSV.generate(options) do |csv|
      csv << direct_export_fields + ping_export_fields + merit_export_fields + other_export_fields
      all.each do |recruiter|
        # Add recruiter line
        list = recruiter.recruiter_list.present? ? recruiter.recruiter_list.name : nil
        recruiter_line = recruiter.attributes.values_at(*direct_export_fields)
        recruiter_line += [nil] * ping_export_fields.length
        recruiter_line += [nil] * merit_export_fields.length
        recruiter_line += [recruiter.score, list]
        csv << recruiter_line

        # Add ping lines
        if recruiter.pings
          recruiter.pings.each do |ping|
            ping_attributes = ping_export_fields.collect{|f| f.split('.').last}
            ping_line = [CSV_PING_MARKER, nil, recruiter.email, nil, nil]
            ping_line += ping.attributes.values_at(*ping_attributes)
            ping_line += [nil] * merit_export_fields.length
            ping_line += [nil] * other_export_fields.length
            csv << ping_line
          end
        end

        # Add merit lines
        if recruiter.merits
          recruiter.merits.each do |merit|
            merit_attributes = merit_export_fields.collect{|f| f.split('.').last}
            merit_line = [CSV_MERIT_MARKER, nil, recruiter.email, nil, nil]
            merit_line += [nil] * ping_export_fields.length
            merit_line += merit.attributes.values_at(*merit_attributes)
            merit_line += [nil]
            csv << merit_line
          end
        end
      end
    end
  end

  #
  # Instance Methods
  #
  def force_rescore
    # Public alias of compute_score. Called by scorable concern.
    compute_score
  end

  def blacklist(reason=nil, color='black')
    blacklist = blacklists.where(color: color).first

    # If blacklisted, nothing to do
    return if blacklist.present? && blacklist.active?

    # Validate and blacklist
    self.transaction do

      # If inactive blacklist, activate
      if blacklist.present?
        blacklist.update_attributes({reason: reason, active: true})

      # If no blacklist, create
      else
        blacklist = Blacklist.new(recruiter_id: id,
                                  color: color,
                                  reason: reason,
                                  active: true)

        # http://stackoverflow.com/a/2718330/1093087
        unless blacklist.valid?
          blacklist.errors.full_messages.each do |msg|
            errors[:base] << "Blacklist Error: #{msg}"
          end

          raise ActiveRecord::Rollback
        end

        blacklist.save!
      end

      # Save demerit
      Merit.create!(
        recruiter_id: id,
        reason: blacklist.color == 'gray' ? 'Graylisted!' : 'Blacklisted!',
        value: blacklist.demerit_value,
        date: Date.today
      )

      # Reload merits and recompute score
      merits(true)
      save!
    end

    blacklist
  end

  def graylist(reason)
    blacklist(reason, 'gray')
  end

  def unblacklist(color='black')
    blacklist = blacklists.where(color: color, active: true).first
    return true if blacklist.nil?

    self.transaction do
      blacklist.update_attribute(:active, false)

      # Save demerit
      Merit.create!(
        recruiter_id: id,
        reason: blacklist.color == 'gray' ? 'Un-graylisted!' : 'Un-blacklisted!',
        value: (blacklist.demerit_value * -0.8).to_i,
        date: Date.today
      )

      # Reload merits and recompute score
      merits(true)
      save!
    end

    true
  end

  def ungraylist
    unblacklist('gray')
  end

  #
  # Fields / Virtual Fields
  #
  def phone=(value)
    self[:phone] = value.gsub(/[^\d+x]/, "") if value
  end

  def phone
    return nil if self[:phone].nil?
    self[:phone].split('x').first
  end

  def phone_extension
    return nil if self[:phone].nil?
    if self[:phone].split('x').length > 0
      self[:phone].split('x')[1]
    end
  end

  def email=(value)
    self[:email] = value.downcase if value
  end

  def name
    format('%s %s', self.first_name, self.last_name)
  end

  def last_contact
    pings.any? ? pings.order('date DESC').first.date : nil
  end

  def timeline
    events = pings + merits + interviews
    events.sort_by{|event| event.date}
  end

  def blacklisted?
    blacklists.where(color: 'black', active: true).any?
  end

  def graylisted?
    blacklists.where(color: 'gray', active: true).any?
  end

  private

  def compute_score
    self[:score] =
      (pings.any? ? (pings.collect{|ping| ping.value}).sum : 0) +
      (merits.any? ? (merits.collect{|merit| merit.value}).sum : 0) +
      (interviews.any? ? (interviews.collect{|interview| interview.value}).sum : 0)
  end
end

app/controllers/recruiters_controller.rb
class RecruitersController < ApplicationController
  before_action :set_recruiter, only: [:show, :edit, :update, :destroy]
  before_action :set_recruiter_lists, only: [:new, :edit]

  # GET /recruiters
  # GET /recruiters.json
  def index
    @search = RecruiterSearch.new(search_params)
    @recruiters = search_params.present? ? @search.results : Recruiter.all.includes(:pings)
    @recruiters = sorted? ? @recruiters.sorted(sort_by, sort_in) : @recruiters.recently_pinged
    @recruiters = (@recruiters.class == Array) ?
      Kaminari.paginate_array(@recruiters).page(params[:page]) :
      @recruiters.page(params[:page])

    # Treat email searches differently
    @is_email_search = @recruiters.blank? && search_params['name_like'] &&
      ValidateEmail.valid?(search_params['name_like'])
    @email = search_params['name_like'] if @is_email_search

    # Flag search to filter blacklisted recruiters in non-search views
    @is_search = search_params.present?

    respond_to do |format|
      format.html
      format.csv { send_data @recruiters.export_to_csv,
        type: 'text/csv; charset=iso-8859-1; header=present',
        disposition: "attachment; filename=recruiters-#{Time.now.strftime('%Y%m%d-%H%M%S')}.csv"
      }
    end
  end

  # GET /recruiters/1
  # GET /recruiters/1.json
  def show
  end

  # GET /recruiters/new
  def new
    @recruiter = Recruiter.new
    @recruiter.email = params['email'] if
      params['email'] && ValidateEmail.valid?(params['email'])
  end

  # GET /recruiters/1/edit
  def edit
  end

  # POST /recruiters
  # POST /recruiters.json
  def create
    @recruiter = Recruiter.new(recruiter_params)

    respond_to do |format|
      if @recruiter.save
        format.html { redirect_to new_recruiter_ping_path(@recruiter),
          notice: 'Recruiter was successfully created. Please add a ping.' }
        format.json { render :show, status: :created, location: @recruiter }
      else
        format.html { render :new }
        format.json { render json: @recruiter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recruiters/1
  # PATCH/PUT /recruiters/1.json
  def update
    respond_to do |format|
      if @recruiter.update(recruiter_params)
        format.html { redirect_to recruiters_path, notice: 'Recruiter was successfully updated.' }
        format.json { render :show, status: :ok, location: @recruiter }
      else
        format.html { render :edit }
        format.json { render json: @recruiter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recruiters/1
  # DELETE /recruiters/1.json
  def destroy
    @recruiter.destroy
    respond_to do |format|
      format.html { redirect_to recruiters_url, notice: 'Recruiter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /recruiters/export
  def export
    respond_to do |format|
      format.csv { send_data Recruiter.sorted_by_email.export_to_csv,
        type: 'text/csv; charset=iso-8859-1; header=present',
        disposition: "attachment; filename=recruiters-#{Time.now.strftime('%Y%m%d-%H%M%S')}.csv"
      }
    end
  end

  # GET /recruiters/import
  def import
  end

  # POST /recruiters/process_import
  def process_import
    recruiters = {
      imported: [],
      duplicated: [],
      invalid: []
    }

    if params[:file].blank?
      flash[:error] = 'Please choose a file.'
      return redirect_to import_recruiters_path
    else
      file = params[:file]
    end

    # Simple file type detection for zip file
    if file.original_filename.ends_with?('.zip')
      require 'zip'
      csv_file = Zip::File.open(file.path).glob('*.csv').first
      file_path = File.join("/tmp", csv_file.name)
      csv_file.extract(file_path) unless File.exist?(file_path)
    else
      file_path = file.path
    end

    # Parse file
    SmarterCSV.process(file_path).each do |row|
      recruiter = Recruiter.create_from_import(row)

      if recruiter.persisted?
        recruiters[:imported] << recruiter
      elsif recruiter.errors.added? :email, :taken
        recruiters[:duplicated] << recruiter
      else
        recruiters[:invalid] << recruiter
      end
    end

    respond_to do |format|
      if recruiters[:imported].length == recruiters.values.map{|a| a.length}.sum
        format.html {
          redirect_to recruiters_path,
          notice: format('All %d recruiters were successfully imported.',
                         recruiters[:imported].length)
        }
      else
        @file_name = file.original_filename
        @recruiters = recruiters
        format.html { render :review_import }
      end
    end
  end

  # GET /recruiters/typeahead/:query
  def typeahead
    @search  = RecruiterSearch.new(typeahead: params[:query])
    render json: @search.results
  end

  # POST /recruiter/1/blacklist.js
  def blacklist
    recruiter = Recruiter.find(params[:id])
    @blacklist = recruiter.blacklist(params[:reason], params[:color])

    respond_to do |format|
      if @blacklist.persisted?
        format.js {
          flash[:notice] = "Recruiter has been #{params[:color]}listed!"
          flash.keep(:notice)
          render js: "window.location = '#{recruiter_path(recruiter)}'"
        }
      else
        format.js { render status: :unprocessable_entity }
      end
    end
  end

  # POST /recruiter/1/unblacklist.js
  def unblacklist
    recruiter = Recruiter.find(params[:id])
    unblacklisted = recruiter.unblacklist(params[:color])

    respond_to do |format|
      if unblacklisted
        format.js {
          flash[:notice] = "Recruiter has been un#{params[:color]}listed!"
          flash.keep(:notice)
          render js: "window.location = '#{recruiter_path(recruiter)}'"
        }
      else
        format.js {
          flash[:danger] = "Unable to un#{params[:color]}list the recruiter."
          flash.keep(:danger)
          render js: "window.location = '#{request.referer}'"
        }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recruiter
    @recruiter = Recruiter.find(params[:id])
  end

  def set_recruiter_lists
    @recruiter_lists = RecruiterList.all
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def recruiter_params
    params.require(:recruiter).permit(:first_name, :last_name, :email, :company, :phone,
                                      :recruiter_list_id)
  end

  def search_params
    params[:recruiter_search] || {}
  end
end

app/helpers/recruiters_helper.rb
module RecruitersHelper
  def score_class(recruiter)
    if recruiter.score > 0
      'positive'
    elsif recruiter.score < 0
      'negative'
    else
      ''
    end
  end
end

app/views/recruiters/_form.html.erb
= form_for @recruiter do |f|
  - if @recruiter.errors.any?
    #error_explanation
      h2 = "#{pluralize(@recruiter.errors.count, "error")} prohibited this recruiter from being saved:"
      ul
        - @recruiter.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :company
    = f.text_field :company
  .field
    = f.label :phone
    = f.text_field :phone
  .actions = f.submit

app/views/recruiters/_form.html.slim
= form_for @recruiter, {class: 'form-horizontal'} do |f|
  - if @recruiter.errors.any?
    #error_explanation
      h2 = "#{pluralize(@recruiter.errors.count, "error")} prohibited this recruiter from being saved:"
      ul
        - @recruiter.errors.full_messages.each do |message|
          li = message

  div.form-group.row
    = f.label :recruiter_list, {class: 'col-sm-2 control-label horizontal'}
    div.col-sm-3
      = f.select(:recruiter_list_id,
          options_for_select(@recruiter_lists.map{ |rl| [rl.name, rl.id] },
                             @recruiter.recruiter_list_id),
          {include_blank: 'Choose list below'},
          {class: "form-control"})
    div.col-sm-7

  div.form-group.row
    = f.label :first_name, {class: 'col-sm-2 control-label horizontal'}
    div.col-sm-3
      = f.text_field :first_name, {class: 'form-control'}
    div.col-sm-7

  div.form-group.row
    = f.label :last_name, {class: 'col-sm-2 control-label horizontal'}
    div.col-sm-3
      = f.text_field :last_name, {class: 'form-control'}
    div.col-sm-7

  div.form-group.row
    = f.label :email, {class: 'col-sm-2 control-label horizontal'}
    div.col-sm-3
      = f.text_field :email, {class: 'form-control'}
    div.col-sm-7

  div.form-group.row
    = f.label :company, {class: 'col-sm-2 control-label horizontal'}
    div.col-sm-3
      = f.text_field :company, {class: 'form-control'}
    div.col-sm-7

  div.form-group.row
    = f.label :phone, {class: 'col-sm-2 control-label horizontal'}
    div.col-sm-3
      = f.text_field :phone, {class: 'form-control'}
    div.col-sm-7

  div.actions.row
    div.col-sm-offset-2.col-sm-10
      = f.submit({class: 'btn btn-primary'})
      a.btn.btn-default href=recruiters_path = 'Cancel'

app/views/recruiters/_search_form.html.slim
div.search.recruiters
  = form_for search, url: recruiters_path, method: :get do |f|
    div.form-group.row
      div.col-sm-3
      div.col-sm-6
        = f.text_field :name_like, {class: 'typeahead form-control',
            placeholder: "Search Name or Email"}
        = f.submit 'Search', {class: 'btn btn-primary'}
      div.col-sm-3.count
        | Showing <strong>#{@recruiters.length}</strong> of
          <strong>#{@recruiters.total_count}</strong> Results

app/views/recruiters/_table.html.slim
table.table.table-striped
  thead
    tr
      th = sortable 'name'
      th = sortable 'email'
      th = sortable 'company'
      th = sortable 'last_contact'
      th = sortable 'score'
      th.actions colspan="5" Actions

  tbody
    - if recruiters.present?
      - recruiters.each do |recruiter|
        - next if recruiter.blacklisted? && !(@is_search)
        tr [
          id="recruiter-#{recruiter.id}"
          class=(['recruiter',
                  ('blacklisted' if recruiter.blacklisted?),
                  ('graylisted' if recruiter.graylisted?)].compact.join(' '))
        ]
          td = link_to recruiter.name, recruiter_path(recruiter)
          td = recruiter.email
          td = recruiter.company
          td = (recruiter.last_contact.present? ? recruiter.last_contact : 'N/A')
          td = recruiter.score
          td
            a.btn.btn-default [
                href=edit_recruiter_path(recruiter)
                title="edit"
              ]
              span.glyphicon.glyphicon-edit aria-hidden="true"
          td
            a.btn.btn-default#ping [
                href=new_recruiter_ping_path(recruiter)
                title="ping / interaction"
              ]
              span.glyphicon.glyphicon-bell aria-hidden="true"
          td
            a.btn.btn-default#interview [
                href=new_interview_path(recruiter_id: recruiter.id)
                title="interview"
              ]
              span.glyphicon.glyphicon-briefcase aria-hidden="true"
          td
            a.btn.btn-default#merit [
                href=new_recruiter_merit_path(recruiter)
                title="Add Merit"
              ]
              span.glyphicon.glyphicon-thumbs-up aria-hidden="true"
          td
            a.btn.btn-default#demerit [
                href=new_recruiter_merit_path(recruiter, demerit: true)
                title="Add Demerit"
              ]
              span.glyphicon.glyphicon-thumbs-down aria-hidden="true"

    - else
      tr
        - if @is_email_search
          td.no-records colspan=10 Recruiter not found.
            #{link_to 'Click here', new_recruiter_path(email: @email)} to create new one.
        - else
          td.no-records colspan=10 No recruiters found.

app/views/recruiters/_timeline.html.slim
table.table.table-striped
  thead
    tr
      th = 'Date'
      th = 'Event'
      th = 'Description'
      th = 'Score'

  tbody
    - recruiter.timeline.reverse.each do |event|
      tr.event
        td = event.date
        td = event.event
        td = event.description
        td = event.value

app/views/recruiters/blacklist.js.slim
- if @blacklist.errors
  - @blacklist.errors.full_messages.each do |message|
    - html_f = "<div class='alert alert-danger' role='alert'><strong>%s</strong>: %s</div>"
    - html_msg = format(html_f, 'Blacklist Error', message).html_safe
    |
      $('div.flash.js').html("#{html_msg}").slideDown(500).delay(3000).slideUp(500);
|
  $('div#blacklist-modal').modal('hide');

app/views/recruiters/edit.html.slim
h2 = @recruiter.name

== render partial: 'form'

div.association
  h3 Pings

  == render partial: 'pings/table', locals: {pings: @recruiter.pings.by_date}

  div.actions
    a.btn.btn-primary.ping [
        href=new_recruiter_ping_path(@recruiter)
        type="button"
      ]
      span.glyphicon.glyphicon-bell aria-hidden="true"
      |  Add Ping

div.association
  h3 Merits / Demerits

  == render partial: 'merits/table', locals: {merits: @recruiter.merits.by_date}

  div.actions
    a.btn.btn-success.merit [
        href=new_recruiter_merit_path(@recruiter)
        type="button"
      ]
      span.glyphicon.glyphicon-thumbs-up aria-hidden="true"
      |  Add Merit

    a.btn.btn-danger.demerit [
        href=new_recruiter_merit_path(@recruiter, demerit: true)
        type="button"
      ]
      span.glyphicon.glyphicon-thumbs-down aria-hidden="true"
      |  Add Demerit

div.association
  h3 Interviews

  == render partial: 'interviews/table', locals: {interviews: @recruiter.interviews.by_date}

  div.actions
    a.btn.btn-primary.interview [
        href=new_interview_path(recruiter_id: @recruiter.id)
        type="button"
      ]
      span.glyphicon.glyphicon-briefcase aria-hidden="true"
      |  Add Interview

div.association
  h3 Blacklist

  div.actions
    - if !(@recruiter.blacklisted?)
      button.btn.btn-black.blacklist [
        data-toggle="modal"
        data-target="#blacklist-modal"
      ]
        span.glyphicon.glyphicon-list aria-hidden="true"
        |  Blacklist
    - else
      = button_to unblacklist_recruiter_path(@recruiter),
        remote: true,
        method: :post,
        class:  "btn btn-default unblacklist",
        data: { confirm: "Are you sure?" } \
        do
        = hidden_field_tag 'color', 'black'
        span.glyphicon.glyphicon-list aria-hidden="true"
        |  De-Blacklist

    - if !(@recruiter.graylisted?)
      button.btn.btn-gray.graylist [
        data-toggle="modal"
        data-target="#blacklist-modal"
      ]
        span.glyphicon.glyphicon-list aria-hidden="true"
        |  Graylist
    - else
      = button_to unblacklist_recruiter_path(@recruiter),
        remote: true,
        method: :post,
        class:  "btn btn-default ungraylist",
        data: { confirm: "Are you sure?" } \
        do
        = hidden_field_tag 'color', 'gray'
        span.glyphicon.glyphicon-list aria-hidden="true"
        |  De-Graylist

/! Blacklist Modal
div.modal [
  id="blacklist-modal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="blacklist-modal-reason"
]
  div.modal-dialog role="document"
    div.modal-content
      div.modal-header
        button.close [
          type="button"
          data-dismiss="modal"
          aria-label="Close"
        ]
          span aria-hidden="true" &times;
        h3.modal-title#blacklist-modal-reason Blacklist Reason
        = form_tag blacklist_recruiter_path(@recruiter), remote: true, method: :post do |f|
          /# Will be overridden dynamically in recruiter.js
          = hidden_field_tag 'color', 'black'
          div.form-group
            = text_field_tag 'reason', nil, {class: 'form-control'}
          div.form-group
            = submit_tag 'Submit', {class: 'btn btn-primary'}

app/views/recruiters/import.html.slim
h2 Import Recruiters

br

= form_tag process_import_recruiters_path, multipart: true do

  div.form-group
    = file_field_tag :file
    p.help-block Supports export files (.csv or .zip) from MailChimp

  div.actions.row
    = submit_tag "Import", {class: 'btn btn-primary'}
    a.btn.btn-default href=recruiters_path = 'Cancel'

app/views/recruiters/index.html.erb
h1 Listing Recruiters

table.table-striped
  thead
    tr
      th First name
      th Last name
      th Email
      th Company
      th Phone
      th
      th
      th

  tbody
    - @recruiters.each do |recruiter|
      tr
        td = recruiter.first_name
        td = recruiter.last_name
        td = recruiter.email
        td = recruiter.company
        td = recruiter.phone
        td = link_to 'Show', recruiter
        td = link_to 'Edit', edit_recruiter_path(recruiter)
        td = link_to 'Destroy', recruiter, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Recruiter', new_recruiter_path

app/views/recruiters/new.html.erb
h1 New Recruiter

== render 'form'

= link_to 'Back', recruiters_path

app/views/recruiters/new.html.slim
h2 Add Recruiter

== render 'form'

= link_to 'Back', recruiters_path

app/views/recruiters/review_import.html.slim
h2 Recruiter Import

h4 = format("File: %s", @file_name)

- [:imported, :invalid, :duplicated].each do |type|
  div class="imported-#{type.to_s}"
    h3 = format('%s Recruiters (%d)', type.to_s.titleize, @recruiters[type].count)

    table.table.table-striped
      thead
        tr
          th Name
          th Email
          th Company

      tbody
        - if @recruiters[type].any?
          - @recruiters[type].each do |recruiter|
            tr.recruiter-id id="recruiter-#{recruiter.id}"
              td = recruiter.name
              td = recruiter.email
              td = recruiter.company
        - else
          tr
            td.centered colspan=3
              strong No recruiters.

br

app/views/recruiters/show.html.erb
p#notice = notice

p
  strong First name:
  = @recruiter.first_name
p
  strong Last name:
  = @recruiter.last_name
p
  strong Email:
  = @recruiter.email
p
  strong Company:
  = @recruiter.company
p
  strong Phone:
  = @recruiter.phone

= link_to 'Edit', edit_recruiter_path(@recruiter)
'|
= link_to 'Back', recruiters_path

app/views/recruiters/show.html.slim
div.row
  - if @recruiter.blacklisted?
    h2.blacklisted Blacklisted
  - elsif @recruiter.graylisted?
    h2.graylisted Graylisted

  div.col-sm-5.recruiter-data
    h2 = @recruiter.name
    h4 = @recruiter.company
    h4 = @recruiter.email
    h4 = number_to_phone(@recruiter.phone, extension: @recruiter.phone_extension, area_code: true)
  div class="col-sm-7 score"
    h4 class="score #{score_class(@recruiter)}" = @recruiter.score

div.actions
  a.btn.btn-primary.edit [
      href=edit_recruiter_path(@recruiter)
      type="button"
    ]
    span.glyphicon.glyphicon-edit aria-hidden="true"
    |  Edit Recruiter

  a.btn.btn-primary.index [
      href=recruiters_path
      type="button"
    ]
    span.glyphicon.glyphicon-home aria-hidden="true"
    |  Recruiters Index

div.timeline
  h3 Timeline
  == render partial: 'timeline', locals: {recruiter: @recruiter}