config/routes.rb
Rails.application.routes.draw do

  resources :recruiters do
    resources :pings
    resources :merits

    collection do
      get :import
      post :process_import
      get :export
    end

    member do
      post :blacklist
      post :unblacklist
    end
  end

  resources :interviews

  resources :recruiter_lists, path: 'lists'

  resources :blacklists, only: [:index]

  get 'recruiters/typeahead/:query' => 'recruiters#typeahead'

  root 'recruiters#index'

end

app/views/layouts/_footer.html.slim
      footer

        p &copy; Some Rights Reserved, 2015
        - if ENV['APP_NAME'] == 'recruiters-on-heroku'
          p please note: database data will be reset periodically

        / Official Google Analytics tracking code (updated 2014-10-23)
        / https://gist.github.com/SteveBenner/7dbcecec3df6ff470d74
        - if Rails.env.production?
          javascript:
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create','#{Rails.configuration.google.analytics.code}','auto');
            ga('send','pageview');

        - else
          /! Google Analytics code suppressed outside production

app/views/layouts/_navbar.html.slim
    nav.navbar.navbar-default.navbar-fixed-top role="navigation"
      .container
        .navbar-header
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="/" Recruiters on Rails
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav
            li= navbar_tab_to "Recruiters", recruiters_path
            li= navbar_tab_to "Interviews", interviews_path
            li= navbar_tab_to "Lists", recruiter_lists_path
            li= navbar_tab_to "Blacklists", blacklists_path
            li= link_to "MailChimp", "https://us10.admin.mailchimp.com/", {target: "_blank"}

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    = viewport_meta_tag
    title= content_for?(:title) ? yield(:title) : "Recruiters on Rails"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"

  body class="#{controller_name} #{action_name}"
    == render partial: "layouts/navbar"

    .container
      .row
        .col-sm-12
          = bootstrap_flash
          div.flash.js
          = yield

      == render partial: "layouts/footer"